from typing import List, Optional, Dict, Any, ClassVar, Type
from marshmallow import Schema
from marshmallow_dataclass import dataclass as mdc
from dataclasses import field
from fortiweb_api.dcs.EndpointBase import EndpointBase
from fortiweb_api.dcs.fortinet.fortiweb.BaseSchema import Baseschema


# rewrite this code to use the marshmallow_dataclass
@mdc(base_schema=Baseschema)
class Global(EndpointBase):
    hostname: str = field(metadata=EndpointBase.post_mark)
    adom_admin: str = field(metadata=EndpointBase.post_mark)
    adom_admin_val: str = field(metadata=EndpointBase.post_mark)
    admin_port: int = field(metadata=EndpointBase.post_mark)
    confsync_enable: str = field(metadata=EndpointBase.post_mark)
    confsync_enable_val: str = field(metadata=EndpointBase.post_mark)
    confsync_port: int = field(metadata=EndpointBase.post_mark)
    admin_sport: int = field(metadata=EndpointBase.post_mark)
    admin_tls_v10: str = field(metadata=EndpointBase.post_mark)
    admin_tls_v10_val: str = field(metadata=EndpointBase.post_mark)
    admin_tls_v11: str = field(metadata=EndpointBase.post_mark)
    admin_tls_v11_val: str = field(metadata=EndpointBase.post_mark)
    admin_tls_v12: str = field(metadata=EndpointBase.post_mark)
    admin_tls_v12_val: str = field(metadata=EndpointBase.post_mark)
    admin_tls_v13: str = field(metadata=EndpointBase.post_mark)
    admin_tls_v13_val: str = field(metadata=EndpointBase.post_mark)
    cli_signature: str = field(metadata=EndpointBase.post_mark)
    cli_signature_val: str = field(metadata=EndpointBase.post_mark)
    dst: str = field(metadata=EndpointBase.post_mark)
    dst_val: str = field(metadata=EndpointBase.post_mark)
    dst_period: int = field(metadata=EndpointBase.post_mark)
    ie6workaround: str = field(metadata=EndpointBase.post_mark)
    ie6workaround_val: str = field(metadata=EndpointBase.post_mark)
    admintimeout: int = field(metadata=EndpointBase.post_mark)
    refresh: int = field(metadata=EndpointBase.post_mark)
    timezone: str = field(metadata=EndpointBase.post_mark)
    timezone_val: str = field(metadata=EndpointBase.post_mark)
    ntpserver: str = field(metadata=EndpointBase.post_mark)
    ntpsync: str = field(metadata=EndpointBase.post_mark)
    ntpsync_val: str = field(metadata=EndpointBase.post_mark)
    syncinterval: int = field(metadata=EndpointBase.post_mark)
    language: str = field(metadata=EndpointBase.post_mark)
    language_val: str = field(metadata=EndpointBase.post_mark)
    auth_timeout: int = field(metadata=EndpointBase.post_mark)
    dh_params: str = field(metadata=EndpointBase.post_mark)
    dh_params_val: str = field(metadata=EndpointBase.post_mark)
    tftp: str = field(metadata=EndpointBase.post_mark)
    tftp_val: str = field(metadata=EndpointBase.post_mark)
    pre_login_banner: str = field(metadata=EndpointBase.post_mark)
    pre_login_banner_val: str = field(metadata=EndpointBase.post_mark)
    maintainer_user: str = field(metadata=EndpointBase.post_mark)
    maintainer_user_val: str = field(metadata=EndpointBase.post_mark)
    admin_https_pki_required: str = field(metadata=EndpointBase.post_mark)
    admin_https_pki_required_val: str = field(metadata=EndpointBase.post_mark)
    https_certificate: str = field(metadata=EndpointBase.post_mark)
    https_certificate_val: str = field(metadata=EndpointBase.post_mark)
    https_intermediate_certificate: str = field(metadata=EndpointBase.post_mark)
    https_intermediate_certificate_val: str = field(metadata=EndpointBase.post_mark)
    fds_proxy: str = field(metadata=EndpointBase.post_mark)
    fds_proxy_val: str = field(metadata=EndpointBase.post_mark)
    record_cli_fail_cmd: str = field(metadata=EndpointBase.post_mark)
    record_cli_fail_cmd_val: str = field(metadata=EndpointBase.post_mark)
    force_us_only: str = field(metadata=EndpointBase.post_mark)
    force_us_only_val: str = field(metadata=EndpointBase.post_mark)
    admin_lockout_threshold: int = field(metadata=EndpointBase.post_mark)
    admin_lockout_duration: int = field(metadata=EndpointBase.post_mark)
    docker_meter_interval: int = field(metadata=EndpointBase.post_mark)
    cert_expire_check_time: int = field(metadata=EndpointBase.post_mark)
    fortiguard_anycast: str = field(metadata=EndpointBase.post_mark)
    fortiguard_anycast_val: str = field(metadata=EndpointBase.post_mark)
    ipv6_dad_ha: str = field(metadata=EndpointBase.post_mark)
    ipv6_dad_ha_val: str = field(metadata=EndpointBase.post_mark)
    updated_debug_log: str = field(metadata=EndpointBase.post_mark)
    updated_debug_log_val: str = field(metadata=EndpointBase.post_mark)
    power_status: str = field(metadata=EndpointBase.post_mark)
    power_status_val: str = field(metadata=EndpointBase.post_mark)
    multi_factor_authentication: str = field(metadata=EndpointBase.post_mark)
    multi_factor_authentication_val: str = field(metadata=EndpointBase.post_mark)
    memory_check: str = field(metadata=EndpointBase.post_mark)
    memory_check_val: str = field(metadata=EndpointBase.post_mark)
    fs_sync_interval: int = field(metadata=EndpointBase.post_mark)
    debug_monitor_interval: int = field(metadata=EndpointBase.post_mark)
    debug_memory_boundary: int = field(metadata=EndpointBase.post_mark)
    console_log: str = field(metadata=EndpointBase.post_mark)
    console_log_val: str = field(metadata=EndpointBase.post_mark)
    debug_get_config: str = field(metadata=EndpointBase.post_mark)
    debug_get_config_val: str = field(metadata=EndpointBase.post_mark)
    shell_access: str = field(metadata=EndpointBase.post_mark)
    shell_access_val: str = field(metadata=EndpointBase.post_mark)
    shell_username: str = field(metadata=EndpointBase.post_mark)
    shell_password: str = field(metadata=EndpointBase.post_mark)
    shell_timeout: int = field(metadata=EndpointBase.post_mark)
    shell_trusthostv4: str = field(metadata=EndpointBase.post_mark)
    shell_trusthostv6: str = field(metadata=EndpointBase.post_mark)
    admin_host_whitelist: str = field(metadata=EndpointBase.post_mark)
    contract_update: str = field(metadata=EndpointBase.post_mark)
    threat_analytics: str = field(metadata=EndpointBase.post_mark)
    threat_analytics_val: str = field(metadata=EndpointBase.post_mark)
    threat_analytics_authurl: str = field(metadata=EndpointBase.post_mark)
    shell_history_size: int = field(metadata=EndpointBase.post_mark)
    admin_forticloud_sso_login: str = field(metadata=EndpointBase.post_mark)
    admin_forticloud_sso_login_val: str = field(metadata=EndpointBase.post_mark)

    Schema: ClassVar[Type[Schema]] = Baseschema

    @classmethod
    def get_post_json_template(cls) -> str:
        cls.post_required_fields = []
        return super().get_post_json_template()

