from typing import List, Optional, Dict, Any, ClassVar, Type

from fortiweb_api.dcs.fortinet.fortiweb.v2_0.cmdb.server_policy.ServerPolicyContentRoutingItem import ServerPolicyContentRoutingItem
from marshmallow import Schema
from marshmallow_dataclass import dataclass as mdc
from dataclasses import field
from fortiweb_api.dcs.fortinet.fortiweb.BaseSchema import Baseschema
from fortiweb_api.dcs.EndpointBase import EndpointBase

@mdc(base_schema=Baseschema)
class ServerPolicy(EndpointBase):
    q_ref: Optional[int]
    q_ref_string: Optional[str]
    name: str = field(metadata=EndpointBase.post_mark | EndpointBase.key_mark)
    deployment_mode: str = field(metadata=EndpointBase.post_mark)
    protocol: str = field(metadata=EndpointBase.post_mark)
    ssl: str = field(metadata=EndpointBase.post_mark)
    implicit_ssl: str = field(metadata=EndpointBase.post_mark)
    vserver: str = field(metadata=EndpointBase.post_mark)
    v_zone: str = field(metadata=EndpointBase.post_mark)
    service: str = field(metadata=EndpointBase.post_mark)
    proxy_protocol: str = field(metadata=EndpointBase.post_mark)
    use_proxy_protocol_addr: str = field(metadata=EndpointBase.post_mark)
    ftp_protection_profile: str = field(metadata=EndpointBase.post_mark)
    web_protection_profile: str = field(metadata=EndpointBase.post_mark)
    replacemsg: str = field(metadata=EndpointBase.post_mark)
    server_pool: str = field(metadata=EndpointBase.post_mark)
    traffic_mirror: str = field(metadata=EndpointBase.post_mark)
    traffic_mirror_profile: str = field(metadata=EndpointBase.post_mark)
    traffic_mirror_type: str = field(metadata=EndpointBase.post_mark)
    allow_hosts: str = field(metadata=EndpointBase.post_mark)
    allow_list: str = field(metadata=EndpointBase.post_mark)
    acceleration_policy: str = field(metadata=EndpointBase.post_mark)
    https_service: str = field(metadata=EndpointBase.post_mark)
    multi_certificate: str = field(metadata=EndpointBase.post_mark)
    adfs_certificate_service: str = field(metadata=EndpointBase.post_mark)
    adfs_certificate_ssl_client_verify: str = field(metadata=EndpointBase.post_mark)
    send_buffers_number: int = field(metadata=EndpointBase.post_mark)
    reply_100_continue: str = field(metadata=EndpointBase.post_mark)
    forward_expect_100_continue: str = field(metadata=EndpointBase.post_mark)
    transaction_based_persistence: str = field(metadata={"firmware":">7.6"} | EndpointBase.post_mark)
    certificate_type: str = field(metadata=EndpointBase.post_mark)
    lets_certificate: str = field(metadata=EndpointBase.post_mark)
    certificate: str = field(metadata=EndpointBase.post_mark)
    certificate_group: str = field(metadata=EndpointBase.post_mark)
    intermediate_certificate_group: str = field(metadata=EndpointBase.post_mark)
    ssl_client_verify: str = field(metadata=EndpointBase.post_mark)
    use_ciphers_group: str = field(metadata=EndpointBase.post_mark)
    ssl_ciphers_group: str = field(metadata=EndpointBase.post_mark)
    tls_v10: str = field(metadata=EndpointBase.post_mark)
    tls_v11: str = field(metadata=EndpointBase.post_mark)
    tls_v12: str = field(metadata=EndpointBase.post_mark)
    tls_v13: str = field(metadata=EndpointBase.post_mark)
    ssl_noreg: str = field(metadata=EndpointBase.post_mark)
    ssl_cipher: str = field(metadata=EndpointBase.post_mark)
    ssl_custom_cipher: str = field(metadata=EndpointBase.post_mark)
    tls13_custom_cipher: str = field(metadata=EndpointBase.post_mark)
    rfc7919_comply: str = field(metadata=EndpointBase.post_mark)
    supported_groups: str = field(metadata=EndpointBase.post_mark)
    sni: str = field(metadata=EndpointBase.post_mark)
    sni_certificate: str = field(metadata=EndpointBase.post_mark)
    sni_strict: str = field(metadata=EndpointBase.post_mark)
    urlcert: str = field(metadata=EndpointBase.post_mark)
    urlcert_group: str = field(metadata=EndpointBase.post_mark)
    urlcert_hlen: int = field(metadata=EndpointBase.post_mark)
    case_sensitive: str = field(metadata=EndpointBase.post_mark)
    status: str = field(metadata=EndpointBase.post_mark)
    comment: str = field(metadata=EndpointBase.post_mark)
    block_port: str = field(metadata=EndpointBase.post_mark)
    noparse: str = field(metadata=EndpointBase.post_mark)
    data_capture_port: str = field(metadata=EndpointBase.post_mark)
    monitor_mode: str = field(metadata=EndpointBase.post_mark)
    web_cache: str = field(metadata=EndpointBase.post_mark)
    http_to_https: str = field(metadata=EndpointBase.post_mark)
    redirect_naked_domain: str = field(metadata=EndpointBase.post_mark)
    sessioncookie_enforce: str = field(metadata=EndpointBase.post_mark)
    syncookie: str = field(metadata=EndpointBase.post_mark)
    half_open_threshold: int = field(metadata=EndpointBase.post_mark)
    client_certificate_forwarding: str = field(metadata=EndpointBase.post_mark)
    client_certificate_forwarding_sub_header: str = field(metadata=EndpointBase.post_mark)
    client_certificate_forwarding_cert_header: str = field(metadata=EndpointBase.post_mark)
    http_pipeline: str = field(metadata=EndpointBase.post_mark)
    hsts_header: str = field(metadata=EndpointBase.post_mark)
    hsts_max_age: int = field(metadata=EndpointBase.post_mark)
    hsts_include_subdomains: str = field(metadata=EndpointBase.post_mark)
    hsts_preload: str = field(metadata=EndpointBase.post_mark)
    hpkp_header: str = field(metadata=EndpointBase.post_mark)
    prefer_current_session: str = field(metadata=EndpointBase.post_mark)
    sz_http_content_routing_list: int = field(metadata=EndpointBase.post_mark)
    client_real_ip: str = field(metadata=EndpointBase.post_mark)
    real_ip_addr: str = field(metadata=EndpointBase.post_mark)
    client_real_ip_random_port: str = field(metadata=EndpointBase.post_mark)
    http2: str = field(metadata=EndpointBase.post_mark)
    tcp_recv_timeout: int = field(metadata=EndpointBase.post_mark)
    http_header_timeout: int = field(metadata=EndpointBase.post_mark)
    tcp_conn_timeout: int = field(metadata=EndpointBase.post_mark)
    internal_cookie_httponly: str = field(metadata=EndpointBase.post_mark)
    internal_cookie_secure: str = field(metadata=EndpointBase.post_mark)
    internal_cookie_samesite: str = field(metadata=EndpointBase.post_mark)
    internal_cookie_samesite_value: str = field(metadata=EndpointBase.post_mark)
    content_security_policy_inline: str = field(metadata=EndpointBase.post_mark)
    ssl_quiet_shutdown: str = field(metadata=EndpointBase.post_mark)
    ssl_session_timeout: int = field(metadata=EndpointBase.post_mark)
    client_timeout: int = field(metadata=EndpointBase.post_mark)
    retry_on: str = field(metadata=EndpointBase.post_mark)
    retry_on_cache_size: int = field(metadata=EndpointBase.post_mark)
    retry_on_connect_failure: str = field(metadata=EndpointBase.post_mark)
    retry_times_on_connect_failure: int = field(metadata=EndpointBase.post_mark)
    retry_on_http_layer: str = field(metadata=EndpointBase.post_mark)
    retry_times_on_http_layer: int = field(metadata=EndpointBase.post_mark)
    retry_on_http_response_codes: str = field(metadata=EndpointBase.post_mark)
    replacemsg_on_connect_failure: str = field(metadata=EndpointBase.post_mark)
    chunk_encoding: str = field(metadata=EndpointBase.post_mark)
    payload_based_content_type: str = field(metadata=EndpointBase.post_mark)
    tlog: str = field(metadata=EndpointBase.post_mark)
    web_cache_storage: str = field(metadata=EndpointBase.post_mark)
    scripting: str = field(metadata=EndpointBase.post_mark)
    scripting_list: str = field(metadata=EndpointBase.post_mark)
    ztna_profile: str = field(metadata=EndpointBase.post_mark)
    tags: str = field(metadata=EndpointBase.post_mark)
    http_parse_max_size: int = field(metadata=EndpointBase.post_mark)
    #some_crap : str = field(metadata={"firmware":">7.6"})

    http_content_routing_list: List[ServerPolicyContentRoutingItem] = field(default_factory=list)


    Schema: ClassVar[Type[Schema]] = Baseschema



    @classmethod
    def get_post_json_template(cls) -> str:
        cls.post_required_fields = []
        return super().get_post_json_template()

